package pojo;
// Generated Oct 11, 2021 2:01:27 AM by Hibernate Tools 4.3.1

import DAO.DAOuser;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ManagedBean;

/**
 * Tblcarlist generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Tblcarlist implements java.io.Serializable {

    private Integer idSearch;

    private Integer id;
    private String username;
    private String custname;
    private String custphone;
    private String carType;
    private String platNumber;
    private String carColor;
    private String domicile;

    public Tblcarlist() {
    }

//         public void save_carlist()
//     {
//         DAOuser add = new DAOuser();
//         add.add_carlist(this);
//     }
    public Tblcarlist(Integer id, String username, String custname, String custphone, String carType, String platNumber, String carColor, String domicile) {

        this.id = id;
        this.username = username;
        this.custname = custname;
        this.custphone = custphone;
        this.carType = carType;
        this.platNumber = platNumber;
        this.carColor = carColor;
        this.domicile = domicile;
    }

    public String getCustphone() {
        return custphone;
    }

    public void setCustphone(String custphone) {
        this.custphone = custphone;
    }

    public String getCustname() {
        return custname;
    }

    public void setCustname(String custname) {
        this.custname = custname;
    }

    public ArrayList<Tblcarlist> getData() {
        DAOuser dao = new DAOuser();
        ArrayList<Tblcarlist> list = dao.getById();
        return list;
    }

    public void search() {
        DAOuser dao = new DAOuser();
        Tblcarlist model = dao.searchData(idSearch);
        System.out.println(model.username.toString());
        username = model.username;
        custname = model.custname;
        custphone = model.custphone;
        carType = model.carType;
        platNumber = model.platNumber;
        carColor = model.carColor;
        domicile = model.domicile;

    }

//    public ArrayList<Tblcarlist> getDatasearch(){
//        DAOuser dao = new DAOuser();
//        ArrayList<Tblcarlist> list = dao.getIddata();
//        return list;
//    }
    public String update() {
        DAOuser dao = new DAOuser();
        dao.updateData(idSearch, carType, username, custname, custphone, platNumber, carColor, domicile);

        return "addcar.xhtml";
    }

    public void delete() {
        DAOuser dao = new DAOuser();
        dao.delete(idSearch);
    }
    
        public String add() {
        DAOuser add = new DAOuser();
        add.add_data(this);
        return "sukses";

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCarType() {
        return this.carType;
    }

    public void setCarType(String carType) {
        this.carType = carType;
    }

    public String getPlatNumber() {
        return this.platNumber;
    }

    public void setPlatNumber(String platNumber) {
        this.platNumber = platNumber;
    }

    public String getCarColor() {
        return this.carColor;
    }

    public void setCarColor(String carColor) {
        this.carColor = carColor;
    }

    public String getDomicile() {
        return this.domicile;
    }

    public void setDomicile(String domicile) {
        this.domicile = domicile;
    }

    public Integer getIdSearch() {
        return idSearch;
    }

    public void setIdSearch(Integer idSearch) {
        this.idSearch = idSearch;
    }

}
